"""
Behavior tests for the order status history API endpoint.
"""

from uuid import UUID, uuid4

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from app.core.auth import get_current_user_data
from app.database.connection import get_db
from app.database.models.order import OrderStatus
from app.main import app
from app.schemas.order import OrderCreate
from app.services.order import cancel_order, create_order


TENANT_ID = UUID(
    "25291ef5-0240-4042-aabc-b92c5aa4957a"
)

OTHER_TENANT_ID = UUID(
    "00000000-0000-0000-0000-000000000001"
)

USER_ID = UUID(
    "00000000-0000-0000-0000-000000000010"
)

BRANCH_ID = UUID(
    "6146f071-baf4-40e9-bbff-71f86e0a7770"
)

PRODUCT_VARIANT_ID = UUID(
    "7c065b06-1422-446b-a163-d6a30b4b659b"
)

NON_EXISTENT_ORDER_ID = UUID(
    "00000000-0000-0000-0000-000000000099"
)


def _create_test_order(db: Session) -> dict:
    """
    Create a real database order for API behavior tests.
    """
    order_data = OrderCreate(
        branch_id=BRANCH_ID,
        customer_id=None,
        customer_address_id=None,
        order_number=(
            f"TEST-API-HISTORY-{uuid4().hex[:8]}"
        ),
        order_type="DINE_IN",
        note="API status history behavior test.",
        items=[
            {
                "product_variant_id": PRODUCT_VARIANT_ID,
                "quantity": 1,
            }
        ],
    )

    return create_order(
        db=db,
        tenant_id=TENANT_ID,
        data=order_data,
    )


@pytest.fixture
def authenticated_client(
    db_session: Session,
):
    """
    Provide a TestClient with authentication and database
    dependencies overridden for integration-style API tests.
    """
    tenant_context = {
        "tenant_id": TENANT_ID,
    }

    original_overrides = (
        app.dependency_overrides.copy()
    )

    def override_current_user() -> dict[str, UUID]:
        return {
            "user_id": USER_ID,
            "tenant_id": tenant_context["tenant_id"],
        }

    def override_get_db():
        yield db_session

    app.dependency_overrides[
        get_current_user_data
    ] = override_current_user

    app.dependency_overrides[
        get_db
    ] = override_get_db

    client = TestClient(app)

    try:
        yield client, tenant_context

    finally:
        app.dependency_overrides.clear()
        app.dependency_overrides.update(
            original_overrides
        )


def test_order_status_history_api_returns_initial_and_cancelled_history(
    authenticated_client,
    db_session: Session,
):
    """
    Verify that the API returns the actual status history
    generated by the order workflow.
    """
    client, _ = authenticated_client

    created_order = _create_test_order(
        db=db_session,
    )

    cancel_order(
        db=db_session,
        tenant_id=TENANT_ID,
        order_id=created_order["id"],
    )

    response = client.get(
        f"/api/v1/orders/"
        f"{created_order['id']}/status-history"
    )

    assert response.status_code == 200

    payload = response.json()

    assert len(payload) == 2

    assert payload[0]["order_id"] == str(
        created_order["id"]
    )
    assert payload[0]["from_status"] is None
    assert (
        payload[0]["to_status"]
        == OrderStatus.REGISTERED.value
    )
    assert payload[0]["changed_at"] is not None

    assert payload[1]["order_id"] == str(
        created_order["id"]
    )
    assert (
        payload[1]["from_status"]
        == OrderStatus.REGISTERED.value
    )
    assert (
        payload[1]["to_status"]
        == OrderStatus.CANCELLED.value
    )
    assert payload[1]["changed_at"] is not None


def test_order_status_history_api_returns_404_for_missing_order(
    authenticated_client,
):
    """
    Verify that requesting history for a non-existent
    order returns HTTP 404.
    """
    client, _ = authenticated_client

    response = client.get(
        f"/api/v1/orders/"
        f"{NON_EXISTENT_ORDER_ID}/status-history"
    )

    assert response.status_code == 404

    assert response.json() == {
        "detail": "Order not found."
    }


def test_order_status_history_api_enforces_tenant_isolation(
    authenticated_client,
    db_session: Session,
):
    """
    Verify that an order belonging to another tenant
    cannot expose its status history.
    """
    client, tenant_context = authenticated_client

    created_order = _create_test_order(
        db=db_session,
    )

    tenant_context["tenant_id"] = OTHER_TENANT_ID

    response = client.get(
        f"/api/v1/orders/"
        f"{created_order['id']}/status-history"
    )

    assert response.status_code == 404

    assert response.json() == {
        "detail": "Order not found."
    }


def test_order_status_history_api_returns_json_objects(
    authenticated_client,
    db_session: Session,
):
    """
    Verify that the API response contains the expected
    JSON representation of an order status history item.
    """
    client, _ = authenticated_client

    created_order = _create_test_order(
        db=db_session,
    )

    response = client.get(
        f"/api/v1/orders/"
        f"{created_order['id']}/status-history"
    )

    assert response.status_code == 200

    payload = response.json()

    assert len(payload) == 1

    history_item = payload[0]

    assert set(history_item.keys()) == {
        "id",
        "order_id",
        "from_status",
        "to_status",
        "changed_at",
        "note",
    }

    assert history_item["order_id"] == str(
        created_order["id"]
    )

    assert history_item["from_status"] is None

    assert (
        history_item["to_status"]
        == OrderStatus.REGISTERED.value
    )