"""Make customer addresses tenant safe

Revision ID: 0f61e33b9e79
Revises: d474488b01e1
Create Date: 2026-09-13 20:59:05.974266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f61e33b9e79'
down_revision: Union[str, Sequence[str], None] = 'd474488b01e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_addresses_customer_default', 'customer_addresses', ['customer_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.drop_constraint(op.f('fk_customer_addresses_customer_id'), 'customer_addresses', type_='foreignkey')
    op.create_foreign_key('fk_customer_addresses_customer_tenant', 'customer_addresses', 'customers', ['tenant_id', 'customer_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customer_addresses_customer_tenant', 'customer_addresses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_addresses_customer_id'), 'customer_addresses', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_customer_addresses_customer_default', table_name='customer_addresses', postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###
