"""add order kitchen timestamps

Revision ID: 14a7724aac7e
Revises: 9e41297a1a77
Create Date: 2026-09-24 22:47:06.106446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a7724aac7e'
down_revision: Union[str, Sequence[str], None] = '9e41297a1a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('preparing_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ready_at')
    op.drop_column('orders', 'preparing_at')
    # ### end Alembic commands ###
