"""Add purchase item to inventory movements

Revision ID: 203e5ba4546d
Revises: df9da0064480
Create Date: 2026-09-11 18:03:13.397923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "203e5ba4546d"
down_revision: Union[str, Sequence[str], None] = "df9da0064480"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_movements",
        sa.Column(
            "purchase_item_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_inventory_movements_purchase_item_id"),
        "inventory_movements",
        ["purchase_item_id"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_inventory_movements_purchase_item_id",
        "inventory_movements",
        "purchase_items",
        ["purchase_item_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_inventory_movements_purchase_item_id",
        "inventory_movements",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_inventory_movements_purchase_item_id"),
        table_name="inventory_movements",
    )

    op.drop_column(
        "inventory_movements",
        "purchase_item_id",
    )
    # ### end Alembic commands ###