"""Add inventory consumption timestamp to orders

Revision ID: 2f0c7675993f
Revises: bdd79f697aad
Create Date: 2026-09-16 02:36:22.371876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0c7675993f'
down_revision: Union[str, Sequence[str], None] = 'bdd79f697aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('inventory_consumed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'inventory_consumed_at')
    # ### end Alembic commands ###
