"""Create inventory items table

Revision ID: 434e73f028db
Revises: c51e40914fb7
Create Date: 2026-09-07 03:24:47.145654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434e73f028db'
down_revision: Union[str, Sequence[str], None] = 'c51e40914fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'ingredient_id', name='uq_inventory_items_branch_ingredient')
    )
    op.create_index(op.f('ix_inventory_items_branch_id'), 'inventory_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_ingredient_id'), 'inventory_items', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_ingredient_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_branch_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
