"""Link inventory batches to purchase items

Revision ID: 539e5b221d58
Revises: 4ee639602fbd
Create Date: 2026-09-10 00:59:56.484719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539e5b221d58'
down_revision: Union[str, Sequence[str], None] = '4ee639602fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "inventory_batches",
        sa.Column("purchase_item_id", sa.Uuid(), nullable=False),
    )

    op.create_index(
        op.f("ix_inventory_batches_purchase_item_id"),
        "inventory_batches",
        ["purchase_item_id"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_inventory_batches_purchase_item_id",
        "inventory_batches",
        "purchase_items",
        ["purchase_item_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "fk_inventory_batches_purchase_item_id",
        "inventory_batches",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_inventory_batches_purchase_item_id"),
        table_name="inventory_batches",
    )

    op.drop_column(
        "inventory_batches",
        "purchase_item_id",
    )

    # ### end Alembic commands ###
