"""Add tenant-safe user role assignments

Revision ID: 6c3031a30f05
Revises: 2b04cbb7fc35
Create Date: 2026-09-03 21:57:03.220990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3031a30f05'
down_revision: Union[str, Sequence[str], None] = '2b04cbb7fc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(
        "uq_roles_tenant_id",
        "roles",
        ["tenant_id", "id"],
    )

    op.create_unique_constraint(
        "uq_users_tenant_id",
        "users",
        ["tenant_id", "id"],
    )

    op.create_table(
        "user_roles",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["roles.tenant_id", "roles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["users.tenant_id", "users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("user_roles")

    op.drop_constraint(
        "uq_users_tenant_id",
        "users",
        type_="unique",
    )

    op.drop_constraint(
        "uq_roles_tenant_id",
        "roles",
        type_="unique",
    )

    # ### end Alembic commands ###
