"""Create user branch assignments

Revision ID: 80b8ada603b0
Revises: 6c3031a30f05
Create Date: 2026-09-04 13:25:16.334529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b8ada603b0'
down_revision: Union[str, Sequence[str], None] = '6c3031a30f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "user_branches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "branch_id"),
    )

    op.create_index(
        "ix_user_branches_user_primary",
        "user_branches",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = true"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "ix_user_branches_user_primary",
        table_name="user_branches",
    )

    op.drop_table("user_branches")

    # ### end Alembic commands ###
