"""Add kitchen capacity to branches

Revision ID: 9e41297a1a77
Revises: a65437865fd4
Create Date: 2026-09-21 17:41:26.565269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e41297a1a77'
down_revision: Union[str, Sequence[str], None] = 'a65437865fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('kitchen_capacity', sa.Integer(), server_default='5', nullable=False))
    op.create_check_constraint('ck_branches_kitchen_capacity_positive', 'branches', 'kitchen_capacity > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_branches_kitchen_capacity_positive', 'branches', type_='check')
    op.drop_column('branches', 'kitchen_capacity')
    # ### end Alembic commands ###
