"""Add order status history

Revision ID: a65437865fd4
Revises: 2f0c7675993f
Create Date: 2026-09-18 15:22:08.180135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a65437865fd4'
down_revision: Union[str, Sequence[str], None] = '2f0c7675993f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_status_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('order_id', sa.Uuid(), nullable=False),
        sa.Column(
            'from_status',
            postgresql.ENUM(
                'REGISTERED',
                'PREPARING',
                'READY',
                'COMPLETED',
                'CANCELLED',
                name='order_status_enum',
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            'to_status',
            postgresql.ENUM(
                'REGISTERED',
                'PREPARING',
                'READY',
                'COMPLETED',
                'CANCELLED',
                name='order_status_enum',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'changed_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('note', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        op.f('ix_order_status_history_order_id'),
        'order_status_history',
        ['order_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_order_status_history_order_id'),
        table_name='order_status_history',
    )
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
