"""Add delivery address snapshot to orders

Revision ID: bdd79f697aad
Revises: 3c6e01951009
Create Date: 2026-09-15 14:46:31.563526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd79f697aad'
down_revision: Union[str, Sequence[str], None] = '3c6e01951009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_recipient_name', sa.String(length=150), nullable=True))
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('delivery_address_line', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_postal_code', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_postal_code')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_address_line')
    op.drop_column('orders', 'delivery_phone')
    op.drop_column('orders', 'delivery_recipient_name')
    # ### end Alembic commands ###
