"""add expenses

Revision ID: c24c10c5c847
Revises: 14a7724aac7e
Create Date: 2026-09-29 19:09:09.432907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24c10c5c847'
down_revision: Union[str, Sequence[str], None] = '14a7724aac7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('RENT', 'SALARY', 'ELECTRICITY', 'WATER', 'TRANSPORT', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_branch_id'), 'expenses', ['branch_id'], unique=False)
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_branch_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
