"""Add tenant-safe customer address relationship

Revision ID: d474488b01e1
Revises: d8cb04d90030
Create Date: 2026-09-13 14:19:27.092625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd474488b01e1'
down_revision: Union[str, Sequence[str], None] = 'd8cb04d90030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customers_tenant_id_id', 'customers', ['tenant_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customers_tenant_id_id', 'customers', type_='unique')
    # ### end Alembic commands ###
