"""Add customers and customer addresses

Revision ID: d8cb04d90030
Revises: 203e5ba4546d
Create Date: 2026-09-13 02:23:34.230274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cb04d90030'
down_revision: Union[str, Sequence[str], None] = '203e5ba4546d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_customers_tenant_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_customers_tenant_id"),
        "customers",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "customer_addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("recipient_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("address_line", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=30), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name="fk_customer_addresses_customer_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_customer_addresses_tenant_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_customer_addresses_customer_id"),
        "customer_addresses",
        ["customer_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_customer_addresses_tenant_id"),
        "customer_addresses",
        ["tenant_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_customer_addresses_tenant_id"),
        table_name="customer_addresses",
    )

    op.drop_index(
        op.f("ix_customer_addresses_customer_id"),
        table_name="customer_addresses",
    )

    op.drop_constraint(
        "fk_customer_addresses_customer_id",
        "customer_addresses",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_customer_addresses_tenant_id",
        "customer_addresses",
        type_="foreignkey",
    )

    op.drop_table("customer_addresses")

    op.drop_index(
        op.f("ix_customers_tenant_id"),
        table_name="customers",
    )

    op.drop_constraint(
        "fk_customers_tenant_id",
        "customers",
        type_="foreignkey",
    )

    op.drop_table("customers")

    # ### end Alembic commands ###