"""Link inventory movements to batches

Revision ID: df9da0064480
Revises: 539e5b221d58
Create Date: 2026-09-10 13:52:52.301036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9da0064480'
down_revision: Union[str, Sequence[str], None] = '539e5b221d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "inventory_movements",
        sa.Column("inventory_batch_id", sa.Uuid(), nullable=True),
    )

    op.create_index(
        op.f("ix_inventory_movements_inventory_batch_id"),
        "inventory_movements",
        ["inventory_batch_id"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_inventory_movements_inventory_batch_id",
        "inventory_movements",
        "inventory_batches",
        ["inventory_batch_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "fk_inventory_movements_inventory_batch_id",
        "inventory_movements",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_inventory_movements_inventory_batch_id"),
        table_name="inventory_movements",
    )

    op.drop_column(
        "inventory_movements",
        "inventory_batch_id",
    )

    # ### end Alembic commands ###
